[project]
name = "walt-api"
version = "0.1.0"
description = "WALT API"
readme = "README.md"
requires-python = ">=3.14,<3.15"
dependencies = [
    "daytona==0.207.0",
    "fastapi[standard-no-fastapi-cloud-cli]",
    "pydantic-ai-slim[openai-realtime]==2.36.0",
    "pydantic-settings",
]

[dependency-groups]
dev = [
    "pytest",
    "ruff",
    "ty",
]

[build-system]
requires = ["uv_build>=0.12.7,<0.13"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "api"
